// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOqfyB-u4TKoeKTvinbGXb4XiVuzBhFJM',
    appId: '1:1044145325774:web:9752a6d74853701cf6329f',
    messagingSenderId: '1044145325774',
    projectId: 'flutter-login-702a7',
    authDomain: 'flutter-login-702a7.firebaseapp.com',
    storageBucket: 'flutter-login-702a7.firebasestorage.app',
    measurementId: 'G-ZZTE51R06K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9k19CtfHoP6f6zhIMjwfJdAPkA-caJ38',
    appId: '1:1044145325774:android:02686df9c0fffcb8f6329f',
    messagingSenderId: '1044145325774',
    projectId: 'flutter-login-702a7',
    storageBucket: 'flutter-login-702a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqfYtY_PYaYQeID7wRz4zj560Kima1AFY',
    appId: '1:1044145325774:ios:0c2b62281e5db858f6329f',
    messagingSenderId: '1044145325774',
    projectId: 'flutter-login-702a7',
    storageBucket: 'flutter-login-702a7.firebasestorage.app',
    iosBundleId: 'com.example.ecomerceBlocNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqfYtY_PYaYQeID7wRz4zj560Kima1AFY',
    appId: '1:1044145325774:ios:0c2b62281e5db858f6329f',
    messagingSenderId: '1044145325774',
    projectId: 'flutter-login-702a7',
    storageBucket: 'flutter-login-702a7.firebasestorage.app',
    iosBundleId: 'com.example.ecomerceBlocNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6aFC5dzXOSNnw6iK9kTIg730hFHvQr88',
    appId: '1:1044145325774:web:9741c56949a38005f6329f',
    messagingSenderId: '1044145325774',
    projectId: 'flutter-login-702a7',
    authDomain: 'flutter-login-702a7.firebaseapp.com',
    storageBucket: 'flutter-login-702a7.firebasestorage.app',
    measurementId: 'G-WP98HNV2PG',
  );
}
